//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD
    {
        public int Mã_Sản_Phẩm { get; set; }
        public string Tên_Sản_Phẩm { get; set; }
        public Nullable<int> Số_Lượng { get; set; }
        public Nullable<int> Giá_Bán { get; set; }
        public string Tên_Danh_Mục { get; set; }
        public string Tên_Nhãn_Hiệu { get; set; }
        public byte[] Hình_Ảnh { get; set; }
    }
}
