//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamStored
    {
        public string SanPhamID { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string ChiTiet { get; set; }
        public string TenSP { get; set; }
        public string NhanHieuID { get; set; }
    }
}
