//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBanHangEntities : DbContext
    {
        public QuanLyBanHangEntities()
            : base("name=QuanLyBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiNhanh> ChiNhanhs { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NhanHieu> NhanHieux { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TemptSP> TemptSPs { get; set; }
        public virtual DbSet<SanPhamStored> SanPhamStoreds { get; set; }
        public virtual DbSet<DASHBOARD> DASHBOARDs { get; set; }
        public virtual DbSet<View_HoaDon> View_HoaDon { get; set; }
    
        [DbFunction("QuanLyBanHangEntities", "function_timTenKH")]
        public virtual IQueryable<function_timTenKH_Result> function_timTenKH(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<function_timTenKH_Result>("[QuanLyBanHangEntities].[function_timTenKH](@sdt)", sdtParameter);
        }
    
        [DbFunction("QuanLyBanHangEntities", "View_tb_HoaDon")]
        public virtual IQueryable<View_tb_HoaDon_Result> View_tb_HoaDon(string hoaDonID)
        {
            var hoaDonIDParameter = hoaDonID != null ?
                new ObjectParameter("HoaDonID", hoaDonID) :
                new ObjectParameter("HoaDonID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<View_tb_HoaDon_Result>("[QuanLyBanHangEntities].[View_tb_HoaDon](@HoaDonID)", hoaDonIDParameter);
        }
    
        public virtual int DeleteChiNhanh(string chiNhanhId)
        {
            var chiNhanhIdParameter = chiNhanhId != null ?
                new ObjectParameter("ChiNhanhId", chiNhanhId) :
                new ObjectParameter("ChiNhanhId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteChiNhanh", chiNhanhIdParameter);
        }
    
        public virtual int DeleteDanhMuc(string danhMucId)
        {
            var danhMucIdParameter = danhMucId != null ?
                new ObjectParameter("DanhMucId", danhMucId) :
                new ObjectParameter("DanhMucId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDanhMuc", danhMucIdParameter);
        }
    
        public virtual int DeleteNhanHieu(string nhanHieuID)
        {
            var nhanHieuIDParameter = nhanHieuID != null ?
                new ObjectParameter("NhanHieuID", nhanHieuID) :
                new ObjectParameter("NhanHieuID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteNhanHieu", nhanHieuIDParameter);
        }
    
        public virtual int DeleteNhanVien(string nhanVienID)
        {
            var nhanVienIDParameter = nhanVienID != null ?
                new ObjectParameter("NhanVienID", nhanVienID) :
                new ObjectParameter("NhanVienID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteNhanVien", nhanVienIDParameter);
        }
    
        public virtual int DeleteSanPham(Nullable<int> sanPhamID)
        {
            var sanPhamIDParameter = sanPhamID.HasValue ?
                new ObjectParameter("SanPhamID", sanPhamID) :
                new ObjectParameter("SanPhamID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteSanPham", sanPhamIDParameter);
        }
    
        public virtual int DeleteTempSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTempSP");
        }
    
        public virtual int InsertChiNhanh(string chiNhanhId, string tenChiNhanh)
        {
            var chiNhanhIdParameter = chiNhanhId != null ?
                new ObjectParameter("ChiNhanhId", chiNhanhId) :
                new ObjectParameter("ChiNhanhId", typeof(string));
    
            var tenChiNhanhParameter = tenChiNhanh != null ?
                new ObjectParameter("TenChiNhanh", tenChiNhanh) :
                new ObjectParameter("TenChiNhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertChiNhanh", chiNhanhIdParameter, tenChiNhanhParameter);
        }
    
        public virtual int InsertChiTietHoaDon(string hoaDonID, Nullable<int> sanPhamID, Nullable<int> soLuong, Nullable<int> donGia, Nullable<int> giamGia, Nullable<int> thanhTien)
        {
            var hoaDonIDParameter = hoaDonID != null ?
                new ObjectParameter("HoaDonID", hoaDonID) :
                new ObjectParameter("HoaDonID", typeof(string));
    
            var sanPhamIDParameter = sanPhamID.HasValue ?
                new ObjectParameter("SanPhamID", sanPhamID) :
                new ObjectParameter("SanPhamID", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var giamGiaParameter = giamGia.HasValue ?
                new ObjectParameter("GiamGia", giamGia) :
                new ObjectParameter("GiamGia", typeof(int));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertChiTietHoaDon", hoaDonIDParameter, sanPhamIDParameter, soLuongParameter, donGiaParameter, giamGiaParameter, thanhTienParameter);
        }
    
        public virtual int InsertDanhMuc(string danhMucID, string tenDanhMuc)
        {
            var danhMucIDParameter = danhMucID != null ?
                new ObjectParameter("DanhMucID", danhMucID) :
                new ObjectParameter("DanhMucID", typeof(string));
    
            var tenDanhMucParameter = tenDanhMuc != null ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertDanhMuc", danhMucIDParameter, tenDanhMucParameter);
        }
    
        public virtual int InsertHoaDon(string khachHangID, string hoaDonID, string maNV, Nullable<System.DateTime> ngayBan, Nullable<int> tongTien)
        {
            var khachHangIDParameter = khachHangID != null ?
                new ObjectParameter("KhachHangID", khachHangID) :
                new ObjectParameter("KhachHangID", typeof(string));
    
            var hoaDonIDParameter = hoaDonID != null ?
                new ObjectParameter("HoaDonID", hoaDonID) :
                new ObjectParameter("HoaDonID", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var ngayBanParameter = ngayBan.HasValue ?
                new ObjectParameter("NgayBan", ngayBan) :
                new ObjectParameter("NgayBan", typeof(System.DateTime));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHoaDon", khachHangIDParameter, hoaDonIDParameter, maNVParameter, ngayBanParameter, tongTienParameter);
        }
    
        public virtual int InsertKhachHang(string khachHangID, string hovaLot, string ten, string sdt)
        {
            var khachHangIDParameter = khachHangID != null ?
                new ObjectParameter("KhachHangID", khachHangID) :
                new ObjectParameter("KhachHangID", typeof(string));
    
            var hovaLotParameter = hovaLot != null ?
                new ObjectParameter("HovaLot", hovaLot) :
                new ObjectParameter("HovaLot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertKhachHang", khachHangIDParameter, hovaLotParameter, tenParameter, sdtParameter);
        }
    
        public virtual int InsertNhanHieu(string nhanHieuId, string tenNhanHieu)
        {
            var nhanHieuIdParameter = nhanHieuId != null ?
                new ObjectParameter("NhanHieuId", nhanHieuId) :
                new ObjectParameter("NhanHieuId", typeof(string));
    
            var tenNhanHieuParameter = tenNhanHieu != null ?
                new ObjectParameter("TenNhanHieu", tenNhanHieu) :
                new ObjectParameter("TenNhanHieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertNhanHieu", nhanHieuIdParameter, tenNhanHieuParameter);
        }
    
        public virtual int InsertNhanVien(string maNV, string tenNV, string matKhau, string chucVu, string maNQL, string chiNhanhID, string luong)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var maNQLParameter = maNQL != null ?
                new ObjectParameter("MaNQL", maNQL) :
                new ObjectParameter("MaNQL", typeof(string));
    
            var chiNhanhIDParameter = chiNhanhID != null ?
                new ObjectParameter("ChiNhanhID", chiNhanhID) :
                new ObjectParameter("ChiNhanhID", typeof(string));
    
            var luongParameter = luong != null ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertNhanVien", maNVParameter, tenNVParameter, matKhauParameter, chucVuParameter, maNQLParameter, chiNhanhIDParameter, luongParameter);
        }
    
        public virtual int InsertSP(Nullable<int> sanPhamID, string chiTiet, string tenSP, Nullable<int> soLuong, Nullable<int> giaNhap, Nullable<int> giaBan, string nhaCungCap, string nhanHieuID, string danhMucID, byte[] hinhAnh)
        {
            var sanPhamIDParameter = sanPhamID.HasValue ?
                new ObjectParameter("SanPhamID", sanPhamID) :
                new ObjectParameter("SanPhamID", typeof(int));
    
            var chiTietParameter = chiTiet != null ?
                new ObjectParameter("ChiTiet", chiTiet) :
                new ObjectParameter("ChiTiet", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(int));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(int));
    
            var nhaCungCapParameter = nhaCungCap != null ?
                new ObjectParameter("NhaCungCap", nhaCungCap) :
                new ObjectParameter("NhaCungCap", typeof(string));
    
            var nhanHieuIDParameter = nhanHieuID != null ?
                new ObjectParameter("NhanHieuID", nhanHieuID) :
                new ObjectParameter("NhanHieuID", typeof(string));
    
            var danhMucIDParameter = danhMucID != null ?
                new ObjectParameter("DanhMucID", danhMucID) :
                new ObjectParameter("DanhMucID", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertSP", sanPhamIDParameter, chiTietParameter, tenSPParameter, soLuongParameter, giaNhapParameter, giaBanParameter, nhaCungCapParameter, nhanHieuIDParameter, danhMucIDParameter, hinhAnhParameter);
        }
    
        public virtual int InsertTempSP(Nullable<int> iD, Nullable<int> soluong, string ten, Nullable<int> donGia)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("Soluong", soluong) :
                new ObjectParameter("Soluong", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTempSP", iDParameter, soluongParameter, tenParameter, donGiaParameter);
        }
    
        public virtual ObjectResult<RUDChiNhanh_Result> RUDChiNhanh(string chiNhanhID, string tenChiNhanh, string statementType)
        {
            var chiNhanhIDParameter = chiNhanhID != null ?
                new ObjectParameter("ChiNhanhID", chiNhanhID) :
                new ObjectParameter("ChiNhanhID", typeof(string));
    
            var tenChiNhanhParameter = tenChiNhanh != null ?
                new ObjectParameter("TenChiNhanh", tenChiNhanh) :
                new ObjectParameter("TenChiNhanh", typeof(string));
    
            var statementTypeParameter = statementType != null ?
                new ObjectParameter("StatementType", statementType) :
                new ObjectParameter("StatementType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUDChiNhanh_Result>("RUDChiNhanh", chiNhanhIDParameter, tenChiNhanhParameter, statementTypeParameter);
        }
    
        public virtual ObjectResult<RUDNhanHieu_Result> RUDNhanHieu(string nhanHieuID, string tenNhanHieu, string statementType)
        {
            var nhanHieuIDParameter = nhanHieuID != null ?
                new ObjectParameter("NhanHieuID", nhanHieuID) :
                new ObjectParameter("NhanHieuID", typeof(string));
    
            var tenNhanHieuParameter = tenNhanHieu != null ?
                new ObjectParameter("TenNhanHieu", tenNhanHieu) :
                new ObjectParameter("TenNhanHieu", typeof(string));
    
            var statementTypeParameter = statementType != null ?
                new ObjectParameter("StatementType", statementType) :
                new ObjectParameter("StatementType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RUDNhanHieu_Result>("RUDNhanHieu", nhanHieuIDParameter, tenNhanHieuParameter, statementTypeParameter);
        }
    
        public virtual int RUDNhanVien(string maNV, string tenNV, string matKhau, string chucVu, string maNQL, string chiNhanhID, string luong, string statementType)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var maNQLParameter = maNQL != null ?
                new ObjectParameter("MaNQL", maNQL) :
                new ObjectParameter("MaNQL", typeof(string));
    
            var chiNhanhIDParameter = chiNhanhID != null ?
                new ObjectParameter("ChiNhanhID", chiNhanhID) :
                new ObjectParameter("ChiNhanhID", typeof(string));
    
            var luongParameter = luong != null ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(string));
    
            var statementTypeParameter = statementType != null ?
                new ObjectParameter("StatementType", statementType) :
                new ObjectParameter("StatementType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RUDNhanVien", maNVParameter, tenNVParameter, matKhauParameter, chucVuParameter, maNQLParameter, chiNhanhIDParameter, luongParameter, statementTypeParameter);
        }
    
        public virtual ObjectResult<SelectChiNhanh_Result> SelectChiNhanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectChiNhanh_Result>("SelectChiNhanh");
        }
    
        public virtual ObjectResult<SelectChiTietHoaDon_Result> SelectChiTietHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectChiTietHoaDon_Result>("SelectChiTietHoaDon");
        }
    
        public virtual ObjectResult<SelectDanhMuc_Result> SelectDanhMuc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectDanhMuc_Result>("SelectDanhMuc");
        }
    
        public virtual ObjectResult<SelectHoaDon_Result> SelectHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectHoaDon_Result>("SelectHoaDon");
        }
    
        public virtual ObjectResult<SelectKhachHang_Result> SelectKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectKhachHang_Result>("SelectKhachHang");
        }
    
        public virtual ObjectResult<SelectNhanHieu_Result> SelectNhanHieu(string nhanHieuID)
        {
            var nhanHieuIDParameter = nhanHieuID != null ?
                new ObjectParameter("NhanHieuID", nhanHieuID) :
                new ObjectParameter("NhanHieuID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNhanHieu_Result>("SelectNhanHieu", nhanHieuIDParameter);
        }
    
        public virtual ObjectResult<SelectNhanVien_Result> SelectNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectNhanVien_Result>("SelectNhanVien");
        }
    
        public virtual ObjectResult<SelectSanPham_Result> SelectSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectSanPham_Result>("SelectSanPham");
        }
    
        public virtual ObjectResult<SelectTemptSP_Result> SelectTemptSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTemptSP_Result>("SelectTemptSP");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<TimChiNhanh_Result> TimChiNhanh(string chiNhanhId)
        {
            var chiNhanhIdParameter = chiNhanhId != null ?
                new ObjectParameter("ChiNhanhId", chiNhanhId) :
                new ObjectParameter("ChiNhanhId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimChiNhanh_Result>("TimChiNhanh", chiNhanhIdParameter);
        }
    
        public virtual ObjectResult<TimDanhMuc_Result> TimDanhMuc(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimDanhMuc_Result>("TimDanhMuc", textParameter);
        }
    
        public virtual ObjectResult<TimKHSDT_Result> TimKHSDT(string sDT)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKHSDT_Result>("TimKHSDT", sDTParameter);
        }
    
        public virtual ObjectResult<TimKHTenKH_Result> TimKHTenKH(string ten)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKHTenKH_Result>("TimKHTenKH", tenParameter);
        }
    
        public virtual ObjectResult<TimKiemSDT_Result> TimKiemSDT(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimKiemSDT_Result>("TimKiemSDT", sdtParameter);
        }
    
        public virtual ObjectResult<TimNhanHieu_Result> TimNhanHieu(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimNhanHieu_Result>("TimNhanHieu", textParameter);
        }
    
        public virtual ObjectResult<TimSP_Result> TimSP(string text)
        {
            var textParameter = text != null ?
                new ObjectParameter("text", text) :
                new ObjectParameter("text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TimSP_Result>("TimSP", textParameter);
        }
    
        public virtual int UpdateChiNhanh(string chiNhanhId, string tenChiNhanh)
        {
            var chiNhanhIdParameter = chiNhanhId != null ?
                new ObjectParameter("ChiNhanhId", chiNhanhId) :
                new ObjectParameter("ChiNhanhId", typeof(string));
    
            var tenChiNhanhParameter = tenChiNhanh != null ?
                new ObjectParameter("TenChiNhanh", tenChiNhanh) :
                new ObjectParameter("TenChiNhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateChiNhanh", chiNhanhIdParameter, tenChiNhanhParameter);
        }
    
        public virtual int UpdateDanhMuc(string danhMucID, string tenDanhMuc)
        {
            var danhMucIDParameter = danhMucID != null ?
                new ObjectParameter("DanhMucID", danhMucID) :
                new ObjectParameter("DanhMucID", typeof(string));
    
            var tenDanhMucParameter = tenDanhMuc != null ?
                new ObjectParameter("TenDanhMuc", tenDanhMuc) :
                new ObjectParameter("TenDanhMuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDanhMuc", danhMucIDParameter, tenDanhMucParameter);
        }
    
        public virtual int UpdateKhachHang(string khachHangID, string hovaLot, string ten, string sdt)
        {
            var khachHangIDParameter = khachHangID != null ?
                new ObjectParameter("KhachHangID", khachHangID) :
                new ObjectParameter("KhachHangID", typeof(string));
    
            var hovaLotParameter = hovaLot != null ?
                new ObjectParameter("HovaLot", hovaLot) :
                new ObjectParameter("HovaLot", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateKhachHang", khachHangIDParameter, hovaLotParameter, tenParameter, sdtParameter);
        }
    
        public virtual int UpdateNhanHieu(string nhanHieuId, string tenNhanHieu)
        {
            var nhanHieuIdParameter = nhanHieuId != null ?
                new ObjectParameter("NhanHieuId", nhanHieuId) :
                new ObjectParameter("NhanHieuId", typeof(string));
    
            var tenNhanHieuParameter = tenNhanHieu != null ?
                new ObjectParameter("TenNhanHieu", tenNhanHieu) :
                new ObjectParameter("TenNhanHieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNhanHieu", nhanHieuIdParameter, tenNhanHieuParameter);
        }
    
        public virtual int UpdateNhanVien(string maNV, string tenNV, string matKhau, string chucVu, string maNQL, string chiNhanhID, string luong)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var maNQLParameter = maNQL != null ?
                new ObjectParameter("MaNQL", maNQL) :
                new ObjectParameter("MaNQL", typeof(string));
    
            var chiNhanhIDParameter = chiNhanhID != null ?
                new ObjectParameter("ChiNhanhID", chiNhanhID) :
                new ObjectParameter("ChiNhanhID", typeof(string));
    
            var luongParameter = luong != null ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateNhanVien", maNVParameter, tenNVParameter, matKhauParameter, chucVuParameter, maNQLParameter, chiNhanhIDParameter, luongParameter);
        }
    
        public virtual int UpdateSP(Nullable<int> sanPhamID, string chiTiet, string tenSP, Nullable<int> soLuong, Nullable<int> giaNhap, Nullable<int> giaBan, string nhaCungCap, string nhanHieuID, string danhMucID, byte[] hinhAnh)
        {
            var sanPhamIDParameter = sanPhamID.HasValue ?
                new ObjectParameter("SanPhamID", sanPhamID) :
                new ObjectParameter("SanPhamID", typeof(int));
    
            var chiTietParameter = chiTiet != null ?
                new ObjectParameter("ChiTiet", chiTiet) :
                new ObjectParameter("ChiTiet", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(int));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(int));
    
            var nhaCungCapParameter = nhaCungCap != null ?
                new ObjectParameter("NhaCungCap", nhaCungCap) :
                new ObjectParameter("NhaCungCap", typeof(string));
    
            var nhanHieuIDParameter = nhanHieuID != null ?
                new ObjectParameter("NhanHieuID", nhanHieuID) :
                new ObjectParameter("NhanHieuID", typeof(string));
    
            var danhMucIDParameter = danhMucID != null ?
                new ObjectParameter("DanhMucID", danhMucID) :
                new ObjectParameter("DanhMucID", typeof(string));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSP", sanPhamIDParameter, chiTietParameter, tenSPParameter, soLuongParameter, giaNhapParameter, giaBanParameter, nhaCungCapParameter, nhanHieuIDParameter, danhMucIDParameter, hinhAnhParameter);
        }
    
        public virtual int updateUTempSP(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateUTempSP", iDParameter);
        }
    
        public virtual ObjectResult<XemHoaDon_Result> XemHoaDon(string hoaDonID)
        {
            var hoaDonIDParameter = hoaDonID != null ?
                new ObjectParameter("HoaDonID", hoaDonID) :
                new ObjectParameter("HoaDonID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<XemHoaDon_Result>("XemHoaDon", hoaDonIDParameter);
        }
    }
}
