//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HoaDon
    {
        public string HoaDonID { get; set; }
        public string TenNV { get; set; }
        public string KhachHangID { get; set; }
        public string Ten { get; set; }
        public string Sdt { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<int> TongTien { get; set; }
    }
}
